### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by bengalspice** [Jeff-1992/intro-data-capstone-biodiversity#5]
**Code**
- Coding was done picture perfect. Great job!
- The extra effort to delve deeper into the data to make additional discoveries was appreciated!

**Slides**
-  It would have been nice to have picked a theme for the slide deck. Leaving the slides white makes it not only harsh on the eyes but makes the feeling of the slides very stark.
- Be careful about keeping aspect ratio on graphs. The bar graph on statuses looks a bit too elongated and hard to read.
- The analysis between conservation of reptiles versus mammals seems to be missing from your slide deck.
- For the Foot and Mouth study, it should take 1 week in Yellowstone and 2 weeks in Bryce. While to run a full and complete study would take reaching the larger sample size, effects can be measured much sooner. 

### **Overall, Great Job! I would encourage you to play around more with the visualization, maybe customizing colors of the bars or even generating a pie chart for the different species or conservation statuses.**

**Comment by Jeff-1992** [comment]
Sharmeen -Thank-you for reviewing my project.  I've responded with comments on each issue you pointed out.  Do I need to make changes and resubmit or have I met all course requirements?

Thanks again,

Jeff

**Comment by Jeff-1992** [comment]
Sharmeen,

Thanks again for reviewing my project.  Two of your bullets above didn't appear as individual issues so I'd like to comment on them here.

The analysis of reptiles vs mammals was one facet of the larger observation of three distinct groupings of species by conservation status.  I considered giving it a viewgraph, but thought that since it was part of the larger recognition of the three distinct groupings I left it out to keep the focus on the larger message.

In the foot and mouth study, the Jupyter project file directed use of the CodeAcademy sample size calculator , while the Jupyter solution file directed use of the Optimizely sample size calculator.  The results are very different (510 for Optimizely vs 870 for CodeAcademy).  I searched the web and found a third similar calculator (Abtasty) that called for 808 samples.  Because this was more in line with the Code Academy calculator I chose 870 and then rounded up since samples seem to be counted weekly.

Can you pass on to CodeAcademy that their Jupyter project file and their Jupyter solutions file direct the use of two different sample size calculators and that the two calculators provide very different sample sizes?  Either choice allow the student to use what they're learned but having two such different answer is confusing to students just learning the material.

Thanks again,

Jeff

**Comment by Jeff-1992** [comment]
Sharmeen,

I recognized that the status graph was hard to read because the large column on the right pushed all the others too far down to be seen.  How can I modify plt.bar to suppress a dominant column?

Thx,

Jeff

**Comment by bengalspice** [comment]
Since you were required to look at the two comparisons for this capstone, it was expected that you would include those specific comparisons regardless of the extra analysis you did.

You do not have to resubmit. I've already marked your project as completed.

Codecademy is aware of the discrepancy in calculations.
